import type { Metadata } from "next";
import localFont from 'next/font/local'
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";

import TopBar from "@/components/shared/TopBar";
import BottomBar from "@/components/shared/BottomBar";
import LeftSideBar from "@/components/shared/LeftSideBar";
import RightSideBar from "@/components/shared/RightSideBar";

const urbanistMedium = localFont({src: '../../public/fonts/Urbanist-Medium.ttf'})

export const metadata: Metadata = {
  title: "Nomeo Threads 1.0",
  description: "Generated by create next app with typescripts. A threads clone.",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={urbanistMedium.className}>
          <TopBar/>
          <main className="flex flex-row">
            <LeftSideBar/>
            <section className="main-container">
              <div className="w-full">
                {children}
              </div>
            </section>
            <RightSideBar/>
          </main>
          <BottomBar/>
        </body>
      </html>
    </ClerkProvider>
  );
}
