import { Metadata } from "next/types";
import localFont from 'next/font/local'
import { ClerkProvider } from "@clerk/nextjs";
import '../globals.css';

const josefSansRegular = localFont({src: '../../public/fonts/JosefinSans-Regular.ttf'})

export const metadata: Metadata = {
  title: "Nomeo Threads 1.0",
  description: "Generated by create next app with typescripts. A threads clone.",
}

export default function RootLayout({children}:{children: React.ReactNode}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${josefSansRegular.className} bg-dark-1`}>{children}</body>
      </html>
    </ClerkProvider>
  );
}