import { Metadata } from "next/types";
import localFont from 'next/font/local'
import { ClerkProvider } from "@clerk/nextjs";
import '../globals.css';

const urbanistMedium = localFont({src: '../../public/fonts/Urbanist-Medium.ttf'})

export const metadata: Metadata = {
  title: "Nomeo Threads 1.0",
  description: "Generated by create next app with typescripts. A threads clone.",
}

export default function RootLayout({children}:{children: React.ReactNode}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${urbanistMedium.className} bg-dark-1`}>
          <div className="w-full flex items-center justify-center min-h-screen">
            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}